Name: Olaofe Folayinka Oluwatoyosi

Student ID: 991843165

Title: Advanced Python Assignment I (PROG50141)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Part 1**: Load Structured Data
You can either go to Kaggle or to another site that contains a set of data. You may want to choose a
dataset from a topic that you like, as it will make the assignment easier and more enjoyable. Provide a
copy of the dataset in the submission.
1. Load the CSV file into a panda DataFrame.
2. Display the first 5 rows of the dataset.
3. Display column names and data types.

In [2]:
import pandas as pd

df = pd.read_csv('Sales_csv.csv')

print(f"The first 5 rows are: \n {df.head(5)}")

The first 5 rows are: 
    Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0      43  CA-2016-101343  17-Jul-16  22-Jul-16  Standard Class    RA-19885   
1     514  CA-2017-163405  21-Dec-17  25-Dec-17  Standard Class    BN-11515   
2     515  CA-2017-163405  21-Dec-17  25-Dec-17  Standard Class    BN-11515   
3    1606  US-2016-115819  19-Apr-16  24-Apr-16    Second Class    JO-15280   
4    1607  US-2016-115819  19-Apr-16  24-Apr-16    Second Class    JO-15280   

    Customer Name    Segment        Country         City  ... Postal Code  \
0    Ruben Ausman  Corporate  United States  Los Angeles  ...       90049   
1  Bradley Nguyen   Consumer  United States  Los Angeles  ...       90049   
2  Bradley Nguyen   Consumer  United States  Los Angeles  ...       90049   
3   Jas O'Carroll   Consumer  United States  Los Angeles  ...       90049   
4   Jas O'Carroll   Consumer  United States  Los Angeles  ...       90049   

   Region       Product ID         Cat

In [ ]:
print(f'The column names are: \n {df.columns}')

print(f'\n The data types are: \n {df.dtypes}')

The column names are: 
 Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

 The data types are: 
 Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Part 2**: Vectors using pandas and NumPy
1. Select one numeric column as a pandas Series.
2. Convert the column to a NumPy array.
3. Calculate the mean, minimum, and maximum.
4. Increase all values by 10% using vectorized operations.

In [3]:
import numpy as np

Sales_Vector = df['Sales'].to_numpy()

Calculations = ['Mean','Minimum','Maximum']

for calc in Calculations:
    match calc:
        case 'Mean': result = Sales_Vector.mean()
        case 'Minimum': result = Sales_Vector.min()
        case 'Maximum': result = Sales_Vector.max()

    print(f"The {calc} sales is {result}")

print('___________________________________________________________________________________________________________________')

# create vectorized function
increase_by_10_percent = lambda i: i * 1.10

vectorized_increase = np.vectorize(increase_by_10_percent)
print(vectorized_increase(Sales_Vector))



The Mean sales is 229.85800083049827
The Minimum sales is 0.444
The Maximum sales is 22638.48
___________________________________________________________________________________________________________________
[ 85.668    7.293    6.468  ...  15.4     27.6408 581.273 ]


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Part 3**: Arrays and Matrices
1. Select multiple numeric columns.
2. Convert them into a NumPy array (matrix).
3. Display the shape of the array.
4. Compute column-wise means and row-wise sums.

In [4]:
Quantity_Profit = df[['Quantity','Profit']]

new_matrix = np.array(Quantity_Profit)

print(f"The shape of the matrix is: {new_matrix.shape}")

Column_Means = np.mean(new_matrix,axis=0)

Row_Sums = np.sum(new_matrix,axis=1)

print(f"\n The column-wise means are: \n {Column_Means}")
print(f"\n The row-wise sums are: \n {Row_Sums}")



The shape of the matrix is: (9994, 2)

 The column-wise means are: 
 [ 3.78957374 28.65689631]

 The row-wise sums are: 
 [   5.894     4.7901    3.7052 ...   -2.3      -3.9102 -138.431 ]


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Part 4**: Matrix Operations
1. Normalize the matrix values.
2. Transpose the matrix.
3. Multiply the matrix by a scalar.

In [5]:

matrix_min = new_matrix.min()
matrix_max = new_matrix.max()

# Apply Min-Max normalization
normalized_matrix = (new_matrix - matrix_min) / (matrix_max - matrix_min)

print("\nNormalized Matrix (Min-Max):")
print(normalized_matrix)

print("\nTranposed Matrix:")
print(normalized_matrix.T)

print("\n Scalar Multiplication:")
print(normalized_matrix * 10)



Normalized Matrix (Min-Max):
[[0.44013322 0.44025948]
 [0.44019988 0.44011922]
 [0.44013322 0.44011356]
 ...
 [0.44026655 0.43957988]
 [0.44019988 0.4395392 ]
 [0.44033322 0.43043779]]

Tranposed Matrix:
[[0.44013322 0.44019988 0.44013322 ... 0.44026655 0.44019988 0.44033322]
 [0.44025948 0.44011922 0.44011356 ... 0.43957988 0.4395392  0.43043779]]

 Scalar Multiplication:
[[4.40133216 4.40259483]
 [4.40199883 4.40119223]
 [4.40133216 4.40113563]
 ...
 [4.4026655  4.39579881]
 [4.40199883 4.39539201]
 [4.40333217 4.30437787]]


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Part 5**: Wrangling Tasks
You need to perform at least FOUR of the wrangling steps such as:
1. Identify missing values and:
o Fill them using an appropriate strategy (mean, median, mode, or constant), or
o Remove affected rows/columns
(Explain your choice)
2. Rename at least one column to improve clarity.
3. Convert at least one column to a more appropriate data type.
4. Remove duplicate rows (if any).
5. Create one new derived column using existing columns.
6. Filter the dataset to include only relevant rows.

For the first wrangling operation, I am removing the SEGMENT column from our dataset.

This column is not needed for our analysis and may create confusion to stakeholders, and during analysis

See code in next cell below:



In [ ]:
# Removing the Segment column

df = df.drop('Segment',axis=1)
print(df.head(1))

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0      43  CA-2016-101343  17-Jul-16  22-Jul-16  Standard Class    RA-19885   

  Customer Name        Country         City       State  Postal Code Region  \
0  Ruben Ausman  United States  Los Angeles  California        90049   West   

        Product ID         Category Sub-Category  \
0  OFF-ST-10003479  Office Supplies      Storage   

                                       Product Name  Sales  Quantity  \
0  Eldon Base for stackable storage shelf, platinum  77.88         2   

   Discount  Profit  
0       0.0   3.894  
   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0      43  CA-2016-101343  17-Jul-16  22-Jul-16  Standard Class    RA-19885   

  Customer Name        Country         City       State  Postal Code Region  \
0  Ruben Ausman  United States  Los Angeles  California        90049   West   

        Product ID         Category Sub-Category  \
0  OFF-ST-10003479

For the second wrangling operation, I am renaming the PROFIT column to PROFIT/LOSS in our dataset.

This is because, in the data, we have a lot of sales that did not make profits. So it is deceiving to name the column profit, whereas we have quite a number of losses. Naming the column 'Profit/Loss' would tell a better story of the data even by taking a glance.

See code in next cell below:



In [11]:
# Renaming the Profit column

df = df.rename(columns={'Profit':'Profit/Loss'})
print(df.head(1))

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0      43  CA-2016-101343  17-Jul-16  22-Jul-16  Standard Class    RA-19885   

  Customer Name        Country         City       State  Postal Code Region  \
0  Ruben Ausman  United States  Los Angeles  California        90049   West   

        Product ID         Category Sub-Category  \
0  OFF-ST-10003479  Office Supplies      Storage   

                                       Product Name  Sales  Quantity  \
0  Eldon Base for stackable storage shelf, platinum  77.88         2   

   Discount  Profit/Loss  
0       0.0        3.894  


For the third wrangling operation, I am grouping the data by states to find the total Profit/Loss per state.

This summarize analysis would help me to pinpoint which states are performing well in terms of sales e.g. Michigan

See code in next cell below:

In [ ]:
# Grouping
print(df.groupby('State')['Profit/Loss'].sum())

State
Alabama                  5786.8253
Arizona                 -3427.9246
Arkansas                 4008.6871
California              76381.3871
Colorado                -6527.8579
Connecticut              3511.4918
Delaware                 9977.3748
District of Columbia     1059.5893
Florida                 -3399.3017
Georgia                 16250.0433
Idaho                     826.7231
Illinois               -12607.8870
Indiana                 18382.9363
Iowa                     1183.8119
Kansas                    836.4435
Kentucky                11199.6966
Louisiana                2196.1023
Maine                     454.4862
Maryland                 7031.1788
Massachusetts            6785.5016
Michigan                24463.1876
Minnesota               10823.1874
Mississippi              3172.9762
Missouri                 6436.2105
Montana                  1833.3285
Nebraska                 2037.0942
Nevada                   3316.7659
New Hampshire            1706.5028
New Jersey    

For the fourth and final wrangling operation, I am filtering the data to see the orders where me made a loss.

This information is important for the future - so we can understand why this happened and prevent it from happening again.

See code in next cell below:

In [ ]:
# Filtering the dataset for profit less than 0

print('Sales with losses: \n')
print(df[df['Profit/Loss'] == 0][['Order ID', 'Customer Name', 'Profit/Loss']].head(50))

Sales with losses: 

            Order ID       Customer Name  Profit/Loss
4800  CA-2016-138520     Jeremy Lonsdale      -4.8588
4802  CA-2014-112158      David Philippe    -110.4900
4809  US-2017-121251         Gary McGarr     -28.9764
4810  US-2016-112977     Caroline Jumper     -22.0980
4813  US-2016-135923       Carlos Meador     -67.6704
4823  CA-2017-141873        Harry Greene     -15.7176
4829  CA-2017-111556         Carlos Daly     -25.2956
4830  CA-2017-168641      Kelly Andreada     -16.0784
4832  CA-2014-119151      Mike Pelletier     -37.9434
4834  CA-2016-119865  Adam Shillingsburg     -44.1960
4835  US-2017-126060      Dorothy Wardle     -32.2192
4840  US-2015-126977        Peter Fuller     -25.0490
4847  CA-2014-128209           Greg Tran     -50.0980
4850  CA-2016-106243       Greg Matthias     -26.1960
4852  CA-2015-163965       Sung Shariari     -36.2940
4856  US-2017-132031      Parhena Norris     -14.5176
4860  CA-2014-151946       Bobby Trafton     -44.1960
4861  C

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**CONCLUSION**

This assignment has helped understand how to import, handle, and perform operations with data using Python. I am come from a background in ERP systems development and, developing of reports, analyzing data and sifting through millions of transactions is a daily task for me.

Now, I am comfortable with:

1. Importing/Loading data from different sources.
2. Working with Matrices and Vectors
3. Using Numpy and Pandas to work with data and numerical values
4. Filtering, grouping, and updating values/columns within a dataset

Thank you!